default: true

# https://github.com/DavidAnson/markdownlint/blob/main/doc/md001.md
heading-increment: false

# https://github.com/DavidAnson/markdownlint/blob/main/doc/md013.md
line-length:
  line_length: 120
  code_block_line_length: 500
  tables: false
